/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TELA;

import BEAN.Lotes_bean;
import DAO.Lotes_dao;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class Jcadastrar_lote extends javax.swing.JFrame {

    /**
     * Creates new form Jcadastrar_lote
     */
    public Jcadastrar_lote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Caixa_produto = new javax.swing.JTextField();
        Caixa_quantidade = new javax.swing.JTextField();
        Caixa_data = new javax.swing.JTextField();
        Caixa_valor = new javax.swing.JTextField();
        Caixa_alocacao = new javax.swing.JTextField();
        Caixa_fornecedor = new javax.swing.JTextField();
        Botton_cadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Botton_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Caixa_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa_produtoActionPerformed(evt);
            }
        });
        getContentPane().add(Caixa_produto);
        Caixa_produto.setBounds(170, 60, 90, 19);
        getContentPane().add(Caixa_quantidade);
        Caixa_quantidade.setBounds(170, 120, 90, 19);
        getContentPane().add(Caixa_data);
        Caixa_data.setBounds(390, 120, 90, 19);
        getContentPane().add(Caixa_valor);
        Caixa_valor.setBounds(390, 60, 90, 19);
        getContentPane().add(Caixa_alocacao);
        Caixa_alocacao.setBounds(390, 90, 90, 19);
        getContentPane().add(Caixa_fornecedor);
        Caixa_fornecedor.setBounds(170, 90, 90, 19);

        Botton_cadastrar.setText("Cadastrar");
        Botton_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botton_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(Botton_cadastrar);
        Botton_cadastrar.setBounds(250, 220, 110, 25);

        jLabel1.setText("Codigo do produto:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 60, 100, 15);

        jLabel2.setText("Quantidade:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 130, 58, 15);

        jLabel3.setText("Data de validade:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 120, 90, 15);

        jLabel4.setText("Valor:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 60, 29, 15);

        jLabel5.setText("Alocação:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 90, 60, 15);

        jLabel6.setText("Codigo do fornecedor:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 90, 120, 15);

        Botton_cancelar.setText("Cancelar");
        Botton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botton_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Botton_cancelar);
        Botton_cancelar.setBounds(380, 220, 90, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botton_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botton_cadastrarActionPerformed
        try {
            String codigo_produto, valor, quantidade, data_v, alocacao, fornecedor;
            
            codigo_produto = Caixa_produto.getText();
            valor = Caixa_valor.getText();
            quantidade = Caixa_quantidade.getText();
            data_v = Caixa_data.getText();
            alocacao = Caixa_alocacao.getText();
            fornecedor = Caixa_fornecedor.getText();
            
            Lotes_bean l_bean = new Lotes_bean();
            l_bean.setL_produto(parseInt(codigo_produto));
            l_bean.setValor(parseInt(valor));
            l_bean.setQuantidade(parseInt(quantidade));
            l_bean.setData_v(data_v);
            l_bean.setAlocacao(parseInt(alocacao));
            l_bean.setFornecedor(parseInt(fornecedor));
            
            Lotes_dao l_dao = new Lotes_dao();
            l_dao.inserir(l_bean);
            
            Caixa_produto.setText("");
            Caixa_valor.setText("");
            Caixa_quantidade.setText("");
            Caixa_data.setText("");
            Caixa_alocacao.setText("");
            Caixa_fornecedor.setText("");
            
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erro ao cadastrar lote");
        }
        this.dispose();
    }//GEN-LAST:event_Botton_cadastrarActionPerformed

    private void Caixa_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Caixa_produtoActionPerformed

    private void Botton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botton_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_Botton_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jcadastrar_lote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jcadastrar_lote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jcadastrar_lote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jcadastrar_lote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jcadastrar_lote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botton_cadastrar;
    private javax.swing.JButton Botton_cancelar;
    private javax.swing.JTextField Caixa_alocacao;
    private javax.swing.JTextField Caixa_data;
    private javax.swing.JTextField Caixa_fornecedor;
    private javax.swing.JTextField Caixa_produto;
    private javax.swing.JTextField Caixa_quantidade;
    private javax.swing.JTextField Caixa_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
