/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TELA;

import BEAN.Cliente_bean;
import DAO.Cliente_dao;

/**
 *
 * @author Samsung
 */
public class Jcadastrar_cliente extends javax.swing.JFrame {

    /**
     * Creates new form Jcadastrar_cliente
     */
    public Jcadastrar_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Caixa_nome = new javax.swing.JTextField();
        Caixa_telefone = new javax.swing.JTextField();
        Caixa_email = new javax.swing.JTextField();
        Caixa_cpf = new javax.swing.JTextField();
        Caixa_cep = new javax.swing.JTextField();
        Caixa_endereco = new javax.swing.JTextField();
        Caixa_municipio = new javax.swing.JTextField();
        Campo_uf = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Botton_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Caixa_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(Caixa_nome);
        Caixa_nome.setBounds(70, 30, 106, 19);
        getContentPane().add(Caixa_telefone);
        Caixa_telefone.setBounds(270, 30, 120, 19);

        Caixa_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa_emailActionPerformed(evt);
            }
        });
        getContentPane().add(Caixa_email);
        Caixa_email.setBounds(70, 70, 110, 19);

        Caixa_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa_cpfActionPerformed(evt);
            }
        });
        getContentPane().add(Caixa_cpf);
        Caixa_cpf.setBounds(270, 70, 120, 19);
        getContentPane().add(Caixa_cep);
        Caixa_cep.setBounds(70, 110, 110, 19);
        getContentPane().add(Caixa_endereco);
        Caixa_endereco.setBounds(270, 110, 120, 19);
        getContentPane().add(Caixa_municipio);
        Caixa_municipio.setBounds(70, 150, 110, 19);

        Campo_uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        getContentPane().add(Campo_uf);
        Campo_uf.setBounds(270, 150, 120, 24);

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 27, 15);

        jLabel2.setText("Municipio");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 44, 15);

        jLabel3.setText("Telefone");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 30, 50, 15);

        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 70, 28, 15);

        jLabel5.setText("CPF / CNPJ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 70, 53, 15);

        jLabel6.setText("CEP");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 110, 19, 15);

        jLabel7.setText("Endereço");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 110, 50, 15);

        jLabel8.setText("UF");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(210, 150, 34, 15);

        Botton_cadastrar.setText("Cadastrar");
        Botton_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botton_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(Botton_cadastrar);
        Botton_cadastrar.setBounds(280, 240, 100, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Caixa_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Caixa_nomeActionPerformed

    private void Caixa_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Caixa_emailActionPerformed

    private void Caixa_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Caixa_cpfActionPerformed

    private void Botton_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botton_cadastrarActionPerformed
        try {
            
             String nome, email, cpf, telefone, endereco, cep, municipio, uf;
             
             nome = Caixa_nome.getText();
             email = Caixa_email.getText();
             cpf = Caixa_cpf.getText();
             telefone = Caixa_telefone.getText();
             endereco = Caixa_endereco.getText();
             cep = Caixa_cep.getText();
             municipio = Caixa_municipio.getText();
             uf = (String) Campo_uf.getSelectedItem();
             
             
             Cliente_bean c_bean = new Cliente_bean();
             c_bean.setNome(nome);
             c_bean.setEmail(email);
             c_bean.setCpf(cpf);
             c_bean.setTelefone(telefone);
             c_bean.setEndereco(endereco);
             c_bean.setCep(cep);
             c_bean.setMunicipio(municipio);
             c_bean.setUf(uf);
             
             
             
             
             Cliente_dao c_dao =  new Cliente_dao();
             c_dao.inserir(c_bean);
             
             Caixa_nome.setText("");
             Caixa_cep.setText("");
             Caixa_email.setText("");
             Caixa_endereco.setText("");
             Caixa_municipio.setText("");
             Caixa_telefone.setText("");
             Caixa_cpf.setText("");
             
             
            
        } catch (Exception e) {
        }
        this.dispose();
    }//GEN-LAST:event_Botton_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jcadastrar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jcadastrar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jcadastrar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jcadastrar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jcadastrar_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botton_cadastrar;
    private javax.swing.JTextField Caixa_cep;
    private javax.swing.JTextField Caixa_cpf;
    private javax.swing.JTextField Caixa_email;
    private javax.swing.JTextField Caixa_endereco;
    private javax.swing.JTextField Caixa_municipio;
    private javax.swing.JTextField Caixa_nome;
    private javax.swing.JTextField Caixa_telefone;
    private javax.swing.JComboBox<String> Campo_uf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
